name: google_cast_sender_web
description: Web implementation of the google_cast_sender plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: google_cast_sender
    platforms:
      web:
        pluginClass: GoogleCastSenderWeb
        fileName: google_cast_sender_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  google_cast_sender_platform_interface:
    path: ../google_cast_sender_platform_interface
  js: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
