name: google_cast_sender
description: Google Cast Sender implementation
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: google_cast_sender_android
      ios:
        default_package: google_cast_sender_ios
      web:
        default_package: google_cast_sender_web

dependencies:
  flutter:
    sdk: flutter
  google_cast_sender_android:
    path: ../google_cast_sender_android
  # google_cast_sender_ios:
  #   path: ../google_cast_sender_ios
  google_cast_sender_platform_interface:
    path: ../google_cast_sender_platform_interface
  # google_cast_sender_web:
  #   path: ../google_cast_sender_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.6
  very_good_analysis: ^5.1.0
