version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/google_cast_sender"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/google_cast_sender/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/google_cast_sender_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/google_cast_sender_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/google_cast_sender_ios"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/google_cast_sender_linux"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/google_cast_sender_macos"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/google_cast_sender_web"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/google_cast_sender_windows"
    schedule:
      interval: "daily"