name: google_cast_sender_ios
description: iOS implementation of the google_cast_sender plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: google_cast_sender
    platforms:
      ios:
        pluginClass: GoogleCastSenderPlugin
        dartPluginClass: GoogleCastSenderIOS

dependencies:
  flutter:
    sdk: flutter
  google_cast_sender_platform_interface:
    path: ../google_cast_sender_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.1.0
